spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tvseries?stringType=unspecified&ApplicationName=tutorial
    username: pgdbo
    password: sql
logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.lx3: TRACE