spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/tvseries?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
    username: admin
    password: admin
mybatis.configuration.mapUnderscoreToCamelCase: true
logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.lx3: TRACE
    com.lx3.learning.config: INFO #只有为INFO时才能在控制台显示默认配置的一些打印信息，包括密码