spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/tvseries
    username: admin
    password: admin
mybatis.configuration.mapUnderscoreToCamelCase: true
logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.lx3: TRACE